import { merge, reverse, sortBy, values } from 'lodash-es'
import sets from './sets.json'
import { isMobile } from './lib/mobile'

const customs = {
    'SPM': {
        mtg: '/mtg_white.png',
        rune: '#c42c2b',
        cover: '/cover/SPM.png',
        width: '120px',
        bot: '50px',
        strip: '#c42c2b',
        background: 'linear-gradient(#273d6f, #346ca9)',
        bottom: '#346ca9',
    },
    'EOE': {
        mtg: '/mtg_white.png',
        rune: '#b6c90b',
        cover: '/cover/EOE.webp',
        width: '120px',
        bot: '40px',
        strip: '#acc215',
        text: '#39203e',
        background: 'linear-gradient(#984d85, #32182c)',
        bottom: '#32182c',
    },
    'FIN': {
        mtg: '/mtg_black.png',
        rune: '#282529',
        cover: '/cover/FIN.png',
        bot: '40px',
        strip: '#282529',
        background: '#e7e6e6',
        bottom: '#e7e6e6',
    },
    'TDM': {
        mtg: '/mtg_default.png',
        rune: '#b8c3cb',
        cover: '/cover/TDM.webp',
        width: '130px',
        bot: '50px',
        strip: '#b8c3cb',
        text: '#1a1a24',
        background: '#3b4153',
        bottom: '#3b4153',
    },
    'DFT': {
        mtg: '/mtg_default.png',
        rune: '#8c1b1e',
        cover: '/cover/DFT.webp',
        width: '140px',
        bot: '50px',
        strip: '#eab100',
        background: '#7dc6d7',
        bottom: '#7dc6d7',
        
    },
    'INR': {
        mtg: '/mtg_white.png',
        rune: '#b52d31',
        cover: '/cover/INR.png',
        width: '70%',
        bot: '42px',
        strip: '#b52d31',
        background: 'linear-gradient(#263545, #242b30)',
        bottom: '#242b30',
    },
    'FDN': {
        mtg: '/mtg_default.png',
        rune: '#dae0db',
        cover: '/cover/FDN.png',
        width: '90%',
        bot: '42px',
        strip: '#dae0db',
        text: '#212127',
        background: '#212127',
        bottom: '#212127'
    },
    'DSK': {
        mtg: '/mtg_default.png',
        rune: '#c86a97',
        cover: '/cover/DSK.png',
        width: '90%',
        bot: '42px',
        strip: '#b3ceaf',
        text: '#1b1125',
        background: 'linear-gradient(#3e3a57, #1b1125)',
        bottom: '#212127'
    },
    'BLB': {
        mtg: '/mtg_default.png',
        rune: '#a2281a',
        cover: '/cover/BLB.webp',
        bot: '18px',
        strip: '#237043',
        background: 'linear-gradient(#83b2d3 60%, #9d9557 85%, #83b2d3 90%)',
        bottom: '#83b2d3',
    },
    'ACR': {
        mtg: '/mtg_beyond.png',
        rune: 'transparent',
        cover: '/cover/ACR.png',
        width: '90%',
        bot: '42px',
        strip: '#c51a22',
        text: 'white',
        background: '#efefef',
        bottom: '#efefef'
    },
    'MH3': {
        mtg: '/mtg_default.png',
        rune: '#2aa7a0',
        cover: '/cover/MH3.png',
        width: '90%',
        bot: '42px',
        strip: '#f2f5f5',
        text: '#9685a6',
        background: '#cfbfe3',
        bottom: '#cfbfe3'
    },
    'OTJ': {
        mtg: '/mtg_default.png',
        rune: '#122c51',
        cover: '/cover/OTJ.png',
        width: '90%',
        bot: '42px',
        strip: '#eb5e2e',
        text: 'white',
        background: 'linear-gradient(#0f8fb5, #dbd9d8, #ee8b52, #731a16)',
        bottom: '#731a16'
    },
    'PIP': {
        mtg: '/mtg_beyond_white.png',
        rune: 'white',
        cover: '/cover/PIP.png',
        width: '80%',
        bot: '50px',
        strip: '#cdb95e',
        text: 'black',
        background: '#19323b',
        bottom: '#19323b'
    },
    'CLU': {
        mtg: '/mtg_white.png',
        rune: 'white',
        cover: '/cover/CLU.png',
        width: '80%',
        bot: '45px',
        strip: '#e1e1e1',
        text: 'black',
        background: '#0b314c',
        bottom: '#0b314c'
    },
    'MKM': {
        mtg: '/mtg_default.png',
        rune: '#af7259',
        cover: '/cover/MKM.png',
        width: '90%',
        bot: '42px',
        strip: '#3e6080',
        text: 'white',
        background: '#1e2a40',
        bottom: '#1e2a40'
    },
    'RVR': {
        mtg: '/mtg_default.png',
        rune: '#7cc0df',
        cover: '/cover/RVR.png',
        width: '90%',
        bot: '42px',
        strip: '#ce4a23',
        text: 'white',
        background: '#29425d',
        bottom: '#29425d'
    },
    'LCI': {
        mtg: '/mtg_black.png',
        rune: '#432a5b',
        cover: '/cover/LCI.png',
        width: '70%',
        bot: '42px',
        strip: '#de456d',
        text: 'white',
        background: '#96c1eb',
        bottom: '#96c1eb'
    },
    'WHO': {
        mtg: '/mtg_beyond_white.png',
        rune: 'transparent',
        cover: '/cover/WHO.png',
        width: '60%',
        bot: '50px',
        strip: '#17305a',
        text: 'white',
        background: 'linear-gradient(#4c4078, #8db4c2, #654277, #4c4078)',
        bottom: '#4c4078'
    },
    'WOE': {
        mtg: '/mtg_default.png',
        rune: '#194e53',
        cover: '/cover/WOE.png',
        width: '70%',
        bot: '50px',
        strip: '#6c489e',
        text: 'white',
        background: 'linear-gradient(#14466b, #33b2b7, #14466b 90%)',
        bottom: '#14466b'
    },
    'CMM': {
        mtg: '/mtg_default.png',
        rune: '#734a93',
        cover: '/cover/CMM.png',
        width: '100%',
        bot: '32px',
        strip: '#4db560',
        text: 'white',
        background: 'linear-gradient(#484264, #5dba7f, #d6707a, #ddbf55)',
        bottom: '#ddbf55'
    },
    'LTR': {
        mtg: '/mtg_beyond_white.png',
        rune: '#eeb53c',
        cover: '/cover/LTR.png',
        width: '90%',
        bot: '45px',
        strip: '#1b5a50',
        text: 'white',
        background: 'linear-gradient(#a9c9d5, #384d67, #1d2028 90%)',
        bottom: '#1d2028'
    },
    'VOW': {
        mtg: '/mtg_default.png',
        rune: '#b52d31',
        cover: '/cover/VOW.png',
        width: '80%',
        bot: '45px',
        strip: '#b52d31',
        background: 'linear-gradient(#263545, #242b30)',
        bottom: '#242b30',
    },
    'MID': {
        mtg: '/mtg_default.png',
        rune: '#de9927',
        cover: '/cover/MID.png',
        width: '80%',
        bot: '45px',
        strip: '#e48839',
        background: '#2b2b2c',
        bottom: '#2b2b2c',
    },
    'STX': {
        mtg: '/mtg_default.png',
        rune: '#73c0d1',
        cover: '/cover/STX.png',
        width: '90%',
        bot: '55px',
        strip: '#aa735c',
        background: '#552724',
        bottom: '#552724',
    },
    'KLD': {
        mtg: '/mtg_old.png',
        rune: '#a8613c',
        cover: '/cover/KLD.png',
        width: '90%',
        bot: '20px',
        strip: '#081d2e',
        background: 'linear-gradient(#d0dce4, #02afd8)',
        bottom: '#02afd8',
    },
    'SOI': {
        mtg: '/mtg_old.png',
        rune: '#ec253c',
        cover: '/cover/SOI.png',
        width: '70%',
        bot: '45px',
        strip: '#cce0e3',
        text: '#081f3a',
        background: '#081f3a',
        bottom: '#081f3a',
    },
}

export const SETS = merge(sets, customs)

export const SET_ORDER = reverse(sortBy(values(SETS), 'releasedDate')).map(c => c.code)
