import { merge, reverse, sortBy, values } from 'lodash-es'
import sets from './sets.json'
import { isMobile } from './lib/mobile'

const customs = {
    'SPM': {
        mtg: '/mtg_white.png',
        rune: '#c42c2b',
        cover: '/cover/SPM.png',
        width: '120px',
        bot: '50px',
        strip: '#c42c2b',
        background: 'linear-gradient(#273d6f, #346ca9)',
        bottom: '#346ca9',
    },
    'EOE': {
        mtg: '/mtg_white.png',
        rune: '#b6c90b',
        cover: '/cover/EOE.webp',
        width: '120px',
        bot: '40px',
        strip: '#acc215',
        text: '#39203e',
        background: 'linear-gradient(#984d85, #32182c)',
        bottom: '#32182c',
    },
    'FIN': {
        mtg: '/mtg_black.png',
        rune: '#282529',
        cover: '/cover/FIN.png',
        bot: '40px',
        strip: '#282529',
        background: '#e7e6e6',
        bottom: '#e7e6e6',
    },
    'TDM': {
        mtg: '/mtg_default.png',
        rune: '#b8c3cb',
        cover: '/cover/TDM.webp',
        width: '130px',
        bot: '50px',
        strip: '#b8c3cb',
        text: '#1a1a24',
        background: '#3b4153',
        bottom: '#3b4153',
    },
    'DFT': {
        mtg: '/mtg_default.png',
        rune: '#8c1b1e',
        cover: '/cover/DFT.webp',
        width: '140px',
        bot: '50px',
        strip: '#eab100',
        background: '#7dc6d7',
        bottom: '#7dc6d7',
        
    },
    'BLB': {
        mtg: '/mtg_default.png',
        rune: '#a2281a',
        cover: '/cover/BLB.webp',
        bot: '18px',
        strip: '#237043',
        background: 'linear-gradient(#83b2d3 60%, #9d9557 85%, #83b2d3 90%)',
        bottom: '#83b2d3',
    },
    'INR': {
        mtg: '/mtg_white.png',
        rune: '#b52d31',
        cover: '/cover/INR.png',
        width: '70%',
        bot: '42px',
        strip: '#b52d31',
        background: 'linear-gradient(#263545, #242b30)',
        bottom: '#242b30',
    },
    'FDN': {
        mtg: '/mtg_default.png',
        rune: '#dae0db',
        cover: '/cover/FDN.png',
        width: '90%',
        bot: '42px',
        strip: '#dae0db',
        text: '#212127',
        background: '#212127',
        bottom: '#212127'
    },
    'DSK': {
        mtg: '/mtg_default.png',
        rune: '#c86a97',
        cover: '/cover/DSK.png',
        width: '90%',
        bot: '42px',
        strip: '#b3ceaf',
        text: '#1b1125',
        background: 'linear-gradient(#3e3a57, #1b1125)',
        bottom: '#212127'
    },
    'ACR': {
        mtg: '/mtg_beyond.png',
        rune: 'transparent',
        cover: '/cover/ACR.png',
        width: '90%',
        bot: '42px',
        strip: '#c51a22',
        text: 'white',
        background: '#efefef',
        bottom: '#efefef'
    },
    'MKM': {
        mtg: '/mtg_default.png',
        rune: '#af7259',
        cover: '/cover/MKM.png',
        width: '90%',
        bot: '42px',
        strip: '#3e6080',
        text: 'white',
        background: '#1e2a40',
        bottom: '#1e2a40'
    },
    'VOW': {
        mtg: '/mtg_default.png',
        rune: '#b52d31',
        cover: '/cover/VOW.png',
        width: '80%',
        bot: '45px',
        strip: '#b52d31',
        background: 'linear-gradient(#263545, #242b30)',
        bottom: '#242b30',
    },
    'MID': {
        mtg: '/mtg_default.png',
        rune: '#de9927',
        cover: '/cover/MID.png',
        width: '80%',
        bot: '45px',
        strip: '#e48839',
        background: '#2b2b2c',
        bottom: '#2b2b2c',
    },
    'STX': {
        mtg: '/mtg_default.png',
        rune: '#73c0d1',
        cover: '/cover/STX.png',
        width: '90%',
        bot: '55px',
        strip: '#aa735c',
        background: '#552724',
        bottom: '#552724',
    },
    'KLD': {
        mtg: '/mtg_old.png',
        rune: '#a8613c',
        cover: '/cover/KLD.png',
        width: '90%',
        bot: '20px',
        strip: '#081d2e',
        background: 'linear-gradient(#d0dce4, #02afd8)',
        bottom: '#02afd8',
    },
    'SOI': {
        mtg: '/mtg_old.png',
        rune: '#ec253c',
        cover: '/cover/SOI.png',
        width: '70%',
        bot: '45px',
        strip: '#cce0e3',
        text: '#081f3a',
        background: '#081f3a',
        bottom: '#081f3a',
    },
}

export const SETS = merge(sets, customs)

export const SET_ORDER = reverse(sortBy(values(SETS), 'releasedDate')).map(c => c.code)
